### ISSUE TITLE
Snippet lines gets indented for each line

### ISSUE THREAD

**Issue by raidenovski** [Shougo/neosnippet.vim#445]
My snippets gets indented inproperly.

Example snippet:
```
# Kubernetes Deployment
snippet Deployment
alias deploy
    ---
    apiVersion: apps/v1beta2
    kind: Deployment
    metadata:
      name: ${1:name}
      namespace: ${2:default}
      labels:
        app: ${3:$1}
    spec:
      replicas: ${4:1}
      selector:
        matchLabels:
          app: $3
      template:
        metadata:
          labels:
            app: $3
        spec:
          containers:
            - name: ${4:$3}
              image: ${5:image}
```

When inserted, it adds indentation for each new line, like so:
```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: <{1:name}>
        namespace: <`2:default`>
        labels:
                app: <`3:<|1|>`>
                spec:
                        replicas: <`4:1`>
                        selector:
                                matchLabels:
                                        app: <|3|>
                                        template:
                                                metadata:
                                                        labels:
                                                                app: <|3|>
                                                                spec:
                                                                        containers:
                                                                                - name: <`4:<|3|>`>
                                                                                  image: <`5:image`>
```

My vim indentation config:
```
" Indentation config
scriptencoding utf-8

" Use spaces instead of tabs
set expandtab

" Auto indent
set autoindent
set smartindent

" Show tab guides
set list
set listchars=tab:\ ,trail:·"

" Intentation
set tabstop=2
set softtabstop=2
set shiftwidth=2
silent! IndentLinesEnable
```
I have read the docs:
```
If you use hard-tab for indentation inside a snippet file, neosnippet will use
'shiftwidth' instead of Vim indent plugin. This feature is useful while some
languages' indent files do not work very well (e.g.: PHP, Python).
```
But not really sure if this applies because I generaly don't have problems when c/p-ing text.
Not really sure what am I doing wrong and I haven't found anything that might help me online.

Thanks
